### PR TITLE
Include className prop for FormFileUpload

### PR DESCRIPTION
**Pull request by migueliriano**

### CODE REVIEW

**Comment by lipemat** [comment]
Thanks for you contribution @migueliriano! Can you please post the following:

1. Link to documentation showing this attribute is available.

Perhaps you meant to extend the definition with the `ButtonParams`?

**Comment by migueliriano** [comment]
@lipemat - Actually, it doesn't have that attribute directly for FormFileUpload.

FormFileUpload is rendering a button that we can't add a custom className: https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/components/src/form-file-upload/index.js#L27

So, if we want to add a custom style we have to use the `render` method, example:

```js
<FormFileUpload
	render={( { openFileDialog }  ) => (
		<Button onClick={openFileDialog} isPrimary={true} >
			<Dashicon icon={'admin-media'} />
			&nbsp; Select Files
		</Button>
	)}
/>
```

I thought that may we can add the className to the FormFileUpload as an attribute, but I realized that this is not in the documentation so this not going to be correct, any suggestion about how we can apply an extension for button and use it like this:

```js
<FormFileUpload className={'btn-primary'}/>
```

**Comment by lipemat** [comment]
Based on this paragraph in the docs, all attributes supported by `<Button>` may be passed to the `<FormFileUpload>` component.

> The component accepts the following props. Props not included in this set will be passed to the Button component.

You can see this happening on the line you linked to via `{...props}`. 

For full inclusion of the available props, I suggest extending the `FormFileUpload` interface with the `ButtonParams` interface like so.

```ts
export interface FormFileUpload extends ButtonParams {
```

**Comment by migueliriano** [comment]
@lipemat - I just addressed your comment, thanks!

**Review by lipemat — APPROVED** [review]
👍

**Pull request merged**
